// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"ozon-testovoe/internal/entity/comment"
	"ozon-testovoe/internal/entity/post"
)

type CommentConnection struct {
	Edges    []*CommentEdge `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type CommentEdge struct {
	Cursor string           `json:"cursor"`
	Node   *comment.Comment `json:"node"`
}

type CreateCommentInput struct {
	Text     string  `json:"text"`
	Author   string  `json:"author"`
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
}

type CreatePostInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Author  string `json:"author"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PostConnection struct {
	Edges    []*PostEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type PostEdge struct {
	Cursor string     `json:"cursor"`
	Node   *post.Post `json:"node"`
}

type Query struct {
}

type Subscription struct {
}
