package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"ozon-testovoe/graph/generated"
	"ozon-testovoe/graph/model"
	"ozon-testovoe/internal/dataloader"
	"ozon-testovoe/internal/entity/comment"
	"ozon-testovoe/internal/entity/post"

	"github.com/google/uuid"
)

// ID is the resolver for the id field.
func (r *commentResolver) ID(ctx context.Context, obj *comment.Comment) (string, error) {
	return obj.ID().String(), nil
}

// Author is the resolver for the author field.
func (r *commentResolver) Author(ctx context.Context, obj *comment.Comment) (string, error) {
	return obj.Author().String(), nil
}

// ParentID is the resolver for the parentId field.
func (r *commentResolver) ParentID(ctx context.Context, obj *comment.Comment) (*string, error) {
	parentIDPtr := obj.ParentID()
	if parentIDPtr == nil {
		return nil, nil
	}
	str := parentIDPtr.String()

	return &str, nil
}

// PostID is the resolver for the postId field.
func (r *commentResolver) PostID(ctx context.Context, obj *comment.Comment) (string, error) {
	return obj.PostID().String(), nil
}

// Children is the resolver for the children field.
func (r *commentResolver) Children(ctx context.Context, obj *comment.Comment, first *int, after *string) (*model.CommentConnection, error) {
	loaders := dataloader.For(ctx)
	thunk := loaders.CommentChildrenLoader.Load(ctx, obj.ID().String()) // убрали gd.StringKey
	allChildrenInterface, err := thunk()
	if err != nil {
		return nil, err
	}
	allChildren, ok := allChildrenInterface.([]*comment.Comment)
	if !ok || allChildren == nil {
		allChildren = []*comment.Comment{}
	}
	totalLen := len(allChildren)
	limit := 10
	if first != nil {
		limit = *first
	}
	startIdx := 0
	if after != nil {
		afterID, err := uuid.Parse(*after)
		if err != nil {
			return nil, err
		}
		for i, c := range allChildren {
			if c.ID() == afterID {
				startIdx = i + 1
				break
			}
		}
	}
	if startIdx >= totalLen {
		allChildren = []*comment.Comment{}
	} else {
		endIdx := startIdx + limit
		if endIdx > totalLen {
			endIdx = totalLen
		}
		allChildren = allChildren[startIdx:endIdx]
	}
	hasNext := startIdx+limit < totalLen
	edges := make([]*model.CommentEdge, len(allChildren))
	for i, c := range allChildren {
		edges[i] = &model.CommentEdge{
			Cursor: c.ID().String(),
			Node:   c,
		}
	}
	var endCursor *string
	if len(allChildren) > 0 {
		cursor := allChildren[len(allChildren)-1].ID().String()
		endCursor = &cursor
	}
	pageInfo := &model.PageInfo{
		HasNextPage: hasNext,
		EndCursor:   endCursor,
	}

	return &model.CommentConnection{Edges: edges, PageInfo: pageInfo}, nil
}

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*post.Post, error) {
	author, err := uuid.Parse(input.Author)
	if err != nil {
		return nil, err
	}
	return r.PostService.Create(ctx, input.Title, input.Content, author, true)
}

// UpdatePostCommentsEnabled is the resolver for the updatePostCommentsEnabled field.
func (r *mutationResolver) UpdatePostCommentsEnabled(ctx context.Context, id string, enabled bool) (*post.Post, error) {
	strIdToUUID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}
	p, err := r.Resolver.PostService.UpdateCommentsEnabled(ctx, strIdToUUID, enabled)
	if err != nil {
		return nil, err
	}
	return p, nil
}

// CreateComment is the resolver for the createComment field.
func (r *mutationResolver) CreateComment(ctx context.Context, input model.CreateCommentInput) (*comment.Comment, error) {
	postId, err := uuid.Parse(input.PostID)
	if err != nil {
		return nil, err
	}
	authorId, err := uuid.Parse(input.Author)
	if err != nil {
		return nil, err
	}
	var parentID *uuid.UUID
	if input.ParentID != nil {
		pid, err := uuid.Parse(*input.ParentID)
		if err != nil {
			return nil, err
		}
		parentID = &pid
	}
	c, err := r.Resolver.CommentService.Create(ctx, input.Text, authorId, postId, parentID)
	if err != nil {
		return nil, err
	}
	return c, nil
}

// ID is the resolver for the id field.
func (r *postResolver) ID(ctx context.Context, obj *post.Post) (string, error) {
	return obj.ID().String(), nil
}

// Author is the resolver for the author field.
func (r *postResolver) Author(ctx context.Context, obj *post.Post) (string, error) {
	return obj.Author().String(), nil
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *post.Post, first *int, after *string) (*model.CommentConnection, error) {
	loaders := dataloader.For(ctx)
	thunk := loaders.PostCommentsLoader.Load(ctx, obj.ID().String())
	commentsInterface, err := thunk()
	if err != nil {
		return nil, err
	}
	allComments, ok := commentsInterface.([]*comment.Comment)
	if !ok || allComments == nil {
		allComments = []*comment.Comment{}
	}
	totalLen := len(allComments)

	limit := 10
	if first != nil {
		limit = *first
	}
	startIdx := 0
	if after != nil {
		afterID, err := uuid.Parse(*after)
		if err != nil {
			return nil, err
		}
		for i, c := range allComments {
			if c.ID() == afterID {
				startIdx = i + 1
				break
			}
		}
	}
	if startIdx >= totalLen {
		allComments = []*comment.Comment{}
	} else {
		endIdx := startIdx + limit
		if endIdx > totalLen {
			endIdx = totalLen
		}
		allComments = allComments[startIdx:endIdx]
	}
	hasNext := startIdx+limit < totalLen

	edges := make([]*model.CommentEdge, len(allComments))
	for i, c := range allComments {
		edges[i] = &model.CommentEdge{
			Cursor: c.ID().String(),
			Node:   c,
		}
	}
	var endCursor *string
	if len(allComments) > 0 {
		cursor := allComments[len(allComments)-1].ID().String()
		endCursor = &cursor
	}
	pageInfo := &model.PageInfo{
		HasNextPage: hasNext,
		EndCursor:   endCursor,
	}
	return &model.CommentConnection{Edges: edges, PageInfo: pageInfo}, nil
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, first *int, after *string) (*model.PostConnection, error) {
	limit := 10
	if first != nil {
		limit = *first
	}
	posts, endCursor, hasNext, err := r.PostService.List(ctx, limit, after)
	if err != nil {
		return nil, err
	}
	edges := make([]*model.PostEdge, len(posts))
	for i, p := range posts {
		edges[i] = &model.PostEdge{
			Cursor: p.ID().String(),
			Node:   p,
		}
	}
	pageInfo := &model.PageInfo{
		HasNextPage: hasNext,
		EndCursor:   endCursor,
	}
	return &model.PostConnection{Edges: edges, PageInfo: pageInfo}, nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*post.Post, error) {
	idUuid, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}
	return r.PostService.Get(ctx, idUuid)
}

// CommentAdded is the resolver for the commentAdded field.
func (r *subscriptionResolver) CommentAdded(ctx context.Context, postID string) (<-chan *comment.Comment, error) {
	pid, err := uuid.Parse(postID)
	if err != nil {
		return nil, err
	}
	ch := r.CommentService.Subscribe(ctx, pid)
	go func() {
		<-ctx.Done()
		r.CommentService.Unsubscribe(ctx, pid, ch)
	}()
	return ch, nil
}

// Comment returns generated.CommentResolver implementation.
func (r *Resolver) Comment() generated.CommentResolver { return &commentResolver{r} }

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Post returns generated.PostResolver implementation.
func (r *Resolver) Post() generated.PostResolver { return &postResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type (
	commentResolver      struct{ *Resolver }
	mutationResolver     struct{ *Resolver }
	postResolver         struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
)
